# global
title: d5c.me
description: freedom through expression
copyright-year: 2026
timezone: America/New_York
paginate: 10
url: 'https://humanshell.github.io'

# assets
sass:
  sass_dir: assets/css
  style: compressed

# my info
owner:
  name: Dominic Giglio
  avatar: https://s.gravatar.com/avatar/38c5bae94ba60ea37f292e68cf7c2454?s=100
  email: humanshell@gmail.com
  github_url: https://github.com/humanshell
  linkedin_url: http://www.linkedin.com/pub/dominic-giglio/42/721/6b0

# markdown
kramdown:
  syntax_highlighter_opts:
    tab_width: 2
