# global
title: d5c.me
description: freedom through expression
timezone: America/New_York
comments: false
disqus_shortname: d5c
#url: 'http://localhost:4000' # base hostname/protocol for dev site

# assets
sass:
  sass_dir: assets/css
  style: compressed

# my info
owner:
  name: Dominic Giglio
  avatar: https://s.gravatar.com/avatar/639e517ff8357171d75a82427c1ac01a?s=100
  email: humanshell@gmail.com
  twitter_url: https://twitter.com/human_shell
  github_url: https://github.com/humanshell
  instagram_url: https://instagram.com/drinkalcohol420
  linkedin_url: http://www.linkedin.com/pub/dominic-giglio/42/721/6b0

# markdown
kramdown:
  coderay:
    coderay_tab_width: 2
